"""Dọn field `Vietnamese` về THUẦN danh sách nghĩa (user chốt 05/08/2026).

Script MỘT LẦN — chạy xong chuyển vào `_daxong/` ngay trong cùng commit (luật L2).

Luật áp dụng, đúng `data/huongdan/README.md` §2c bản 05/08:
  - chỉ liệt kê nghĩa, ngăn bằng dấu phẩy;
  - CẤM nhãn từ loại/giống/thể/phản thân (bốn badge đã in trên mặt đề bài),
    cấm cách chi phối, cấm lưu ý cách dùng, cấm mệnh đề phủ định "(không phải X)";
  - chỉ nghĩa thông dụng, bỏ nghĩa lóng và nghĩa văn chương;
  - KHÔNG nới rộng: nghĩa nào gloss tiếng Anh của chính thẻ không đỡ thì không viết.

Chạy khan trước (in bảng cũ -> mới, không ghi gì):
    PYTHONIOENCODING=utf-8 python _va_dondebai.py
Ghi thật:
    PYTHONIOENCODING=utf-8 python _va_dondebai.py --apply
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from anki_tools.anki_client import _ac, sync_truoc_khi_ghi_lo

# ---------------------------------------------------------------- bảng nghĩa
# khoá = `WordClean` trong Anki (đã bỏ U+200B), giá trị = field `Vietnamese` mới.
MOI = {
    "а": "nhưng, mà",
    "автомобиль": "ô tô, xe hơi",
    "альбом": "album",
    "англичанин": "người Anh",
    "арбатский": "thuộc về Arbat",
    "бабушка": "bà, bà nội, bà ngoại",
    "балка": "dầm, xà, khe núi",
    "банк": "ngân hàng",
    "банка": "cái lọ, cái hũ, lon",
    "батон": "ổ bánh mì dài, bánh mì que",
    "без": "không có, thiếu, vắng, kém",
    "билет": "vé, thẻ, phiếu đề thi",
    "бить": "đánh, đập, gõ, giáng",
    "близкий": "gần, thân thiết",
    "близко": "gần, ở gần",
    "блузка": "áo kiểu, áo sơ mi nữ",
    "блюдо": "món ăn, đĩa lớn đựng thức ăn",
    "болеть": "bị ốm, đau nhức, cổ vũ",
    "больше": "nhiều hơn, lớn hơn, hơn nữa",
    "большой": "to, lớn, quan trọng, trưởng thành",
    "борщ": "súp củ cải đỏ",
    "брать": "lấy, cầm, mang đi, mượn, thuê",
    "будничный": "thường ngày, tẻ nhạt, đơn điệu",
    "буфет": "quầy ăn nhẹ, tủ búp phê",
    "быль": "chuyện có thật",
    "быть": "là, có, có mặt, tồn tại",
    "бюро": "văn phòng, quầy chỉ dẫn",
    "в": "ở, trong, vào",
    "варенный": "luộc, nấu chín",
    "ваш": "của bạn, của các bạn, của ngài",
    "вдох": "hơi hít vào",
    "ведро": "cái xô, cái thùng",
    "весь": "toàn bộ, cả, tất cả",
    "весёлый": "vui vẻ, vui nhộn, tươi vui",
    "ветреный": "có gió, lộng gió, nhẹ dạ, hay thay đổi",
    "взять": "lấy, cầm, mượn, thuê",
    "видеть": "nhìn thấy, trông thấy",
    "вишня": "quả anh đào chua, cây anh đào chua",
    "вместо": "thay cho, thay vì",
    "войти": "đi vào, bước vào",
    "вокзал": "nhà ga, toà nhà ga",
    "вон": "kia kìa, đằng kia, ra ngoài",
    "вот": "đây này, đây rồi, đó",
    "всегда": "luôn luôn, lúc nào cũng",
    "вставить": "cắm vào, chèn vào, nhét vào",
    "встретиться": "gặp nhau, hẹn gặp",
    "всё": "mọi thứ, tất cả",
    "второй": "thứ hai, thứ nhì",
    "вход": "cửa vào, lối vào, vé vào cửa",
    "вы": "bạn, các bạn, ngài, quý vị",
    "выдох": "hơi thở ra",
    "выйти": "đi ra, bước ra, ra mắt, được xuất bản",
    "выпить": "uống, uống cạn",
    "выполнить": "thực hiện, hoàn thành",
    "высокий": "cao",
    "высоко": "cao, ở trên cao",
    "выучить": "học thuộc, học xong",
    "выход": "lối ra, cửa thoát, cách thoát",
    "газ": "khí, chất khí, ga",
    "гараж": "ga-ra, nhà để xe",
    "гибкий": "dẻo, uốn cong được, linh hoạt",
    "гиря": "quả tạ, tạ chuông",
    "говорить": "nói, trò chuyện, nói được",
    "год": "năm",
    "голова": "đầu",
    "горько": "đắng, cay đắng, đau đớn",
    "горячий": "nóng, nồng nhiệt, nóng tính",
    "государственный": "thuộc nhà nước, thuộc quốc gia, công lập",
    "грамм": "gam",
    "грач": "chim rook, quạ đen",
    "громкий": "to, vang, ầm ĩ",
    "громко": "to tiếng, lớn tiếng",
    "группа": "nhóm, tốp, ban nhạc",
    "грязный": "bẩn, dơ, lấm bùn",
    "гулять": "đi dạo, dạo chơi",
    "давать": "đưa, cho, trao",
    "далёкий": "xa, xa xôi, cách trở",
    "дать": "đưa, cho, trao, cho phép",
    "два": "hai",
    "двухтысячный": "thứ hai nghìn, thuộc năm 2000",
    "дедушка": "ông, ông nội, ông ngoại",
    "делать": "làm, thực hiện, chế tạo",
    "дело": "việc, chuyện, vấn đề, công chuyện",
    "деньга": "tiền, đồng xu cổ",
    "деньги": "tiền, tiền bạc",
    "дерево": "cây, gỗ",
    "джинсы": "quần jean",
    "диалог": "cuộc đối thoại, lời đối đáp",
    "диск": "đĩa tròn, đĩa CD, ổ đĩa",
    "длинный": "dài",
    "для": "cho, dành cho, để",
    "до": "cho tới, đến, trước lúc",
    "добрый": "tốt bụng, nhân hậu, tử tế",
    "доехать": "đi đến nơi, tới nơi",
    "дождливый": "mưa nhiều, hay mưa",
    "долгий": "lâu, dài, kéo dài",
    "дом": "ngôi nhà, toà nhà, gia đình",
    "дома": "ở nhà",
    "домашний": "thuộc nhà, gia đình, tự làm ở nhà",
    "домой": "về nhà",
    "дорога": "con đường, đường đi, chuyến đi",
    "дорогой": "đắt, đắt tiền, quý giá, thân mến",
    "дочь": "con gái",
    "другой": "khác, cái khác, người khác, còn lại",
    "дюйм": "inch",
    "дядя": "chú, bác, cậu",
    "есть": "ăn, có, tồn tại",
    "ехать": "đi, đi bằng xe",
    "ещё": "nữa, thêm nữa, vẫn còn",
    "жаркий": "nóng, nóng nực",
    "жарко": "nóng, trời nóng",
    "ждать": "đợi, chờ, trông đợi",
    "жительство": "sự cư trú, nơi ở",
    "жук": "con bọ cánh cứng, bọ hung",
    "за": "đằng sau, phía sau, vì, đổi lấy, trong vòng",
    "завод": "nhà máy, xí nghiệp",
    "зал": "phòng lớn, sảnh, hội trường, phòng tập",
    "занято": "bận, có người rồi, kín chỗ",
    "запах": "mùi",
    "звать": "gọi, gọi tên, mời",
    "звук": "âm thanh, tiếng, âm",
    "здание": "toà nhà, công trình",
    "здесь": "ở đây, tại đây, chỗ này",
    "здравствовать": "mạnh khoẻ, an khang, trường tồn",
    "здравствуйте": "xin chào",
    "знакомиться": "làm quen",
    "знать": "biết, quen biết",
    "золото": "vàng",
    "зяблик": "chim chaffinch, sẻ ngực hồng",
    "и": "và, cũng, chính là",
    "играть": "chơi, chơi nhạc, đóng vai",
    "идти": "đi, đi bộ, đang đi tới",
    "извинить": "tha lỗi, bỏ qua, thứ lỗi",
    "или": "hoặc, hay là",
    "иногда": "thỉnh thoảng, đôi khi",
    "интересно": "thú vị, cuốn hút, đáng chú ý",
    "инфинитив": "dạng nguyên thể",
    "использовать": "sử dụng, dùng",
    "к": "đến chỗ, tới, hướng về phía",
    "каждый": "mỗi, từng, mọi người",
    "как": "như thế nào, bằng cách nào, như, giống như",
    "какой": "nào, loại nào, thế nào",
    "карман": "túi áo, túi quần",
    "карта": "bản đồ, thẻ, quân bài",
    "картина": "bức tranh, cảnh tượng",
    "картофель": "khoai tây, cây khoai tây",
    "картошка": "khoai tây",
    "касса": "quầy thu ngân, quầy vé, két tiền",
    "квартира": "căn hộ",
    "кеды": "giày vải đế bằng, giày ba ta",
    "киев": "Kiev",
    "кино": "điện ảnh, phim ảnh, rạp chiếu bóng",
    "кинотеатр": "rạp chiếu phim",
    "класс": "lớp học, lớp, phòng học",
    "клуб": "câu lạc bộ, nhà câu lạc bộ",
    "князь": "vương công, công tước",
    "колбаса": "xúc xích, giò",
    "кольцо": "cái nhẫn, cái vòng, khoen",
    "коммуникативный": "thuộc về giao tiếp",
    "комната": "căn phòng, buồng",
    "компания": "hội bạn, nhóm bạn, công ty",
    "компьютер": "máy vi tính, máy tính",
    "корзина": "cái giỏ, cái sọt, thùng rác",
    "короткий": "ngắn",
    "коса": "bím tóc, lưỡi hái, doi cát",
    "костюм": "bộ vest, bộ đồ, trang phục",
    "который": "người mà, cái mà, nào",
    "кошка": "con mèo, mèo cái",
    "красивый": "đẹp, xinh, đẹp trai",
    "крепкий": "chắc, bền, vững, đậm",
    "кровать": "cái giường",
    "круг": "hình tròn, vòng tròn, một vòng",
    "крупный": "to, thô, hạt to, lớn, đáng kể",
    "кто": "ai",
    "куда": "đi đâu, về phía nào, tới đâu",
    "купить": "mua, sắm",
    "куриный": "thuộc về gà, của gà",
    "курс": "khoá học, năm học, tỉ giá, hướng đi",
    "куртка": "áo khoác ngắn, áo jacket",
    "лампа": "cây đèn, bóng đèn",
    "липа": "cây đoan, cây bồ đề",
    "листва": "tán lá, lá cây",
    "лук": "củ hành, cây cung",
    "луна": "mặt trăng",
    "лучше": "tốt hơn, hay hơn, khá hơn",
    "любить": "yêu, thích",
    "лёгкий": "nhẹ, dễ",
    "лёд": "băng, đá, nước đá",
    "магазин": "cửa hàng, tiệm",
    "маленький": "nhỏ, bé",
    "мама": "mẹ, má",
    "марка": "con tem, nhãn hiệu, thương hiệu",
    "масло": "bơ, dầu ăn, dầu",
    "матрёшка": "búp bê gỗ Nga, búp bê lồng nhau",
    "мать": "mẹ, người mẹ",
    "машина": "xe hơi, ô tô, cỗ máy",
    "между": "ở giữa, giữa",
    "меньше": "ít hơn, nhỏ hơn, kém hơn",
    "место": "chỗ, nơi, chỗ ngồi, chỗ làm",
    "метр": "mét",
    "минута": "phút, chốc lát",
    "минутка": "một phút, một thoáng",
    "много": "nhiều, rất nhiều",
    "модель": "người mẫu, mẫu, kiểu",
    "можно": "được, được phép, có thể",
    "молодёжь": "giới trẻ, thanh niên",
    "монах": "thầy tu, tu sĩ, nhà sư",
    "морозный": "giá buốt, có sương giá",
    "москва": "Moscow, sông Moskva",
    "мочь": "có thể, đủ sức",
    "мышь": "con chuột, chuột máy tính",
    "мягкий": "mềm, dịu, êm",
    "на": "trên, ở, vào, tới",
    "настоящий": "thật, đích thực, hiện tại",
    "научиться": "học được, biết làm",
    "национальность": "dân tộc, tộc người",
    "национальный": "thuộc dân tộc, mang bản sắc dân tộc",
    "не": "không",
    "небольшой": "không lớn, nho nhỏ, ngắn",
    "недорогой": "không đắt, phải chăng",
    "некрасивый": "không đẹp, khó coi, xấu",
    "нельзя": "không được, cấm, không thể",
    "немного": "một chút, một ít, hơi",
    "нет": "không, không có, không tồn tại",
    "низкий": "thấp, trầm, hèn hạ",
    "низко": "thấp, ở dưới thấp",
    "ничего": "không gì cả, chẳng có gì, không sao",
    "но": "nhưng",
    "нога": "chân, cẳng chân, bàn chân",
    "ноль": "số không, số 0",
    "номер": "số, số hiệu, phòng khách sạn, số báo",
    "нужный": "cần, cần thiết, đúng thứ cần",
    "нёбо": "vòm miệng",
    "о": "về, nói về, va vào",
    "обида": "nỗi tủi thân, sự phật lòng, điều xúc phạm",
    "облачный": "có mây, nhiều mây, đám mây",
    "обувь": "giày dép",
    "объявить": "thông báo, tuyên bố",
    "объявление": "thông báo, tờ rao vặt, quảng cáo",
    "объём": "thể tích, dung tích, sức chứa, khối lượng",
    "овощ": "rau, rau củ",
    "одежда": "quần áo, trang phục",
    "один": "một, một mình",
    "озеро": "hồ, hồ nước",
    "ой": "ối, ôi, ái",
    "окунь": "cá rô châu Âu, cá perch",
    "он": "anh ấy, ông ấy, nó",
    "орех": "quả hạch, hạt cứng, hạt dẻ",
    "остановка": "trạm dừng, bến xe, sự dừng lại",
    "ответить": "trả lời, đáp lại",
    "ответный": "đáp lại, đáp trả",
    "отвечать": "trả lời, hồi đáp, chịu trách nhiệm",
    "отдыхать": "nghỉ ngơi, xả hơi, đi nghỉ mát",
    "отель": "khách sạn",
    "отец": "cha, bố",
    "отлично": "xuất sắc, tuyệt vời, điểm 5",
    "охота": "việc đi săn, sự thèm muốn",
    "пакет": "cái túi, gói hàng, bưu kiện",
    "палка": "cây gậy, thanh gỗ dài",
    "папа": "bố, ba",
    "пасмурный": "âm u, xám xịt, ủ rũ",
    "пачка": "gói, xấp, bó",
    "первый": "thứ nhất, đầu tiên",
    "передать": "trao lại, chuyển hộ, nhắn hộ, truyền",
    "пересадка": "chuyển tàu xe, quá cảnh, cấy ghép",
    "петь": "hát, ca",
    "письмо": "bức thư, chữ viết, hệ chữ viết",
    "пить": "uống",
    "платье": "váy liền thân, đầm",
    "плач": "sự khóc, tiếng khóc",
    "плохой": "tồi, kém, dở, xấu",
    "площадь": "quảng trường, diện tích",
    "по": "theo, dọc theo, qua, vào",
    "по-русски": "bằng tiếng Nga, theo kiểu Nga",
    "по-французски": "bằng tiếng Pháp, theo kiểu Pháp",
    "повторять": "lặp lại, nhắc lại, ôn lại",
    "поговорить": "nói chuyện một lúc, trò chuyện một hồi",
    "подушка": "cái gối, đệm lót",
    "подъезд": "lối vào chung cư, sảnh cầu thang",
    "подъём": "sự đi lên, sự leo dốc, sự thức dậy, sự tăng trưởng",
    "позавтракать": "ăn sáng",
    "позвонить": "gọi điện thoại, rung chuông",
    "познакомиться": "làm quen, quen được",
    "показать": "cho xem, chìa ra, chỉ ra",
    "покататься": "đi dạo bằng xe, đi trượt",
    "покупать": "mua, sắm",
    "пол": "sàn nhà, nền, giới tính, nửa",
    "положительный": "tích cực, khẳng định, dương",
    "полпервого": "mười hai giờ rưỡi",
    "помнить": "nhớ, ghi nhớ",
    "понимать": "hiểu, nhận ra",
    "понравиться": "thích, thấy ưng ý",
    "попозже": "muộn hơn một chút, lát nữa",
    "порядок": "trật tự, sự ngăn nắp, thứ tự, thủ tục",
    "послезавтра": "ngày kia",
    "послушать": "lắng nghe, nghe một lượt",
    "посмотреть": "xem, nhìn thử",
    "поставить": "đặt đứng, dựng lên, để vào",
    "потанцевать": "nhảy một lát, khiêu vũ một lát",
    "потому": "vì thế, chính vì vậy",
    "почему": "tại sao, vì sao",
    "пощада": "sự tha thứ, sự nương tay",
    "правда": "sự thật, lẽ phải",
    "правильно": "đúng, chính xác",
    "прекрасный": "tuyệt vời, tuyệt đẹp, xuất sắc",
    "преподаватель": "giảng viên, giáo viên đại học",
    "привет": "chào, xin chào",
    "приехать": "đến nơi, tới bằng xe",
    "приятно": "dễ chịu, thấy vui, thú vị",
    "про": "về, nói về, dành cho",
    # Hai ngày dưới đây không nằm trong 457 thẻ có ngoặc, nhưng viết lệch kiểu
    # với năm ngày còn lại (`среда` dùng dấu chấm phẩy, `вторник` không viết hoa)
    # — sửa luôn cho cả bộ bảy ngày cùng một lối.
    "среда": "thứ Tư, môi trường",
    "вторник": "thứ Ba",
    "проверять": "kiểm tra, rà soát, thử",
    "продукт": "sản phẩm, thực phẩm",
    "прослушать": "nghe hết một lượt, nghe trọn",
    "проспект": "đại lộ, tờ giới thiệu",
    "прыжок": "cú nhảy, bước nhảy",
    "прямо": "thẳng, ngay, đúng phóc",
    "пюре": "món nghiền nhuyễn, khoai tây nghiền",
    "пятый": "thứ năm, thứ 5",
    "пёс": "con chó đực, con chó",
    "работать": "làm việc, đi làm, chạy, hoạt động",
    "раз": "lần, một lần, vì",
    "разговаривать": "nói chuyện, trò chuyện",
    "размер": "cỡ, kích thước, kích cỡ",
    "разъём": "giắc cắm, đầu nối, cổng cắm",
    "рассказать": "kể lại, thuật lại",
    "ребята": "các cậu, bọn trẻ, đám bạn",
    "регулярно": "đều đặn, thường xuyên theo lịch",
    "редко": "hiếm khi, ít khi",
    "реплика": "lời đối đáp, câu thoại, lời nhận xét",
    "речка": "con sông nhỏ, con suối",
    "рисовать": "vẽ, phác hoạ",
    "рисунок": "hình vẽ, bản vẽ, hoạ tiết",
    "родиться": "chào đời, được sinh ra",
    "розовый": "màu hồng, hồng",
    "рубашка": "áo sơ mi",
    "рубль": "đồng rúp",
    "рука": "tay, cánh tay, bàn tay, nét chữ",
    "рядом": "ngay cạnh, sát bên, kề bên",
    "с": "cùng với, từ chỗ, khỏi",
    "самый": "nhất, chính là cái đó",
    "сапог": "ủng, giày ống cao cổ",
    "сахар": "đường",
    "свежий": "tươi, mới",
    "связь": "mối liên hệ, sự gắn kết, liên lạc",
    "сдача": "tiền thừa trả lại, sự đầu hàng, sự nộp lại",
    "себя": "bản thân, chính mình",
    "седьмой": "thứ bảy, thứ 7",
    "село": "làng lớn, thôn",
    "семья": "gia đình",
    "серный": "thuộc về lưu huỳnh",
    "сильный": "mạnh, khoẻ, dữ dội, to",
    "сказать": "nói, bảo, kể",
    "сколько": "bao nhiêu, bao lâu",
    "слабый": "yếu, kém, loãng, nhạt",
    "слева": "ở bên trái, từ bên trái",
    "слушать": "nghe, lắng nghe",
    "слышать": "nghe thấy, nghe được",
    "сметана": "kem chua, váng sữa chua",
    "смотреть": "nhìn, xem, ngắm",
    "собор": "nhà thờ lớn, thánh đường",
    "сосиска": "xúc xích",
    "составить": "lập ra, soạn thảo, gộp thành, lên tới",
    "союз": "liên minh, liên hiệp, liên từ",
    "справа": "ở bên phải, từ bên phải",
    "спрашивать": "hỏi, đặt câu hỏi",
    "спросить": "hỏi, hỏi thăm",
    "спрягаться": "được chia theo ngôi",
    "степь": "thảo nguyên",
    "стол": "cái bàn",
    "стоять": "đứng, ở tại chỗ, dừng",
    "студент": "sinh viên",
    "стул": "cái ghế tựa, ghế đẩu",
    "сумка": "túi xách, cặp, túi",
    "суп": "món súp, canh",
    "сцена": "sân khấu, cảnh, màn",
    "съезд": "đại hội, lối rẽ xuống",
    "так": "như thế, theo cách đó, vậy",
    "там": "ở đó, đằng đó",
    "танцевать": "nhảy, khiêu vũ, múa",
    "твой": "của bạn, của anh, của chị, của em",
    "творог": "phô mai tươi dạng hạt",
    "твёрдый": "cứng, rắn, dứt khoát, kiên định",
    "театр": "nhà hát, kịch nghệ",
    "теперь": "bây giờ, giờ thì, ngày nay",
    "теплоход": "tàu thuỷ, tàu du lịch",
    "тип": "loại, kiểu, dạng",
    "тихий": "yên tĩnh, khẽ, êm ả",
    "толстый": "béo, mập, dày",
    "только": "chỉ, mỗi, vừa mới",
    "тот": "cái kia, cái đó, người đó",
    "точка": "dấu chấm, điểm, quan điểm",
    "третий": "thứ ba, thứ 3",
    "троллейбус": "xe buýt điện",
    "трудно": "khó, khó khăn, vất vả",
    "трудный": "khó, hóc búa, gian nan",
    "туда": "đến đó, tới đó, sang đó",
    "тут": "ở đây, chỗ này, ngay lúc ấy",
    "туфля": "giày da, giày tây, giày cao gót",
    "ты": "bạn, anh, chị, em",
    "тяжело": "nặng nề, nặng nhọc, vất vả, khó khăn",
    "тяжёлый": "nặng, nặng nề, vất vả, khó",
    "тёплый": "ấm, ấm áp, nồng hậu",
    "тётя": "dì, cô, bác gái",
    "у": "ở chỗ, cạnh, bên",
    "угол": "góc",
    "ужасный": "khủng khiếp, kinh hoàng, tồi tệ",
    "узкий": "hẹp, chật, hẹp hòi",
    "улица": "đường phố, phố",
    "университет": "trường đại học",
    "утюг": "cái bàn là, bàn ủi",
    "учитель": "thầy giáo, giáo viên",
    "учиться": "học, theo học",
    "фабрика": "nhà máy, xưởng sản xuất",
    "факт": "dữ kiện, sự việc có thật",
    "фильм": "bộ phim",
    "фирма": "hãng, doanh nghiệp",
    "фото": "bức ảnh, tấm hình",
    "фрукт": "trái cây, hoa quả",
    "хвост": "cái đuôi, phần đuôi, hàng dài",
    "хек": "cá hake",
    "ходить": "đi, đi lại, lui tới",
    "холод": "cái lạnh, khí lạnh, trời rét",
    "холодно": "lạnh, trời lạnh",
    "холодный": "lạnh, lạnh lùng",
    "хороший": "tốt, giỏi, khá, hay",
    "хотеть": "muốn, thích, định",
    "хотя": "mặc dù, dù rằng, ít ra",
    "цех": "phân xưởng",
    "цифра": "chữ số, con số",
    "часть": "phần, bộ phận",
    "чашка": "cái tách, chén",
    "через": "qua, xuyên qua, băng qua, sau",
    "четвёртый": "thứ tư, thứ 4",
    "число": "số, số lượng, ngày trong tháng",
    "что": "gì, cái gì, rằng",
    "чтобы": "để, để mà",
    "шапка": "mũ len, mũ ấm, tiêu đề",
    "шар": "khối cầu, quả bóng tròn, bóng bay",
    "шарф": "khăn quàng cổ",
    "шестой": "thứ sáu, thứ 6",
    "широкий": "rộng, rộng rãi, đa dạng",
    "шкаф": "cái tủ đứng, tủ quần áo, tủ sách",
    "штука": "cái, chiếc, thứ, món",
    "шуба": "áo lông thú",
    "щи": "súp bắp cải Nga",
    "щит": "tấm khiên, lá chắn, bảng",
    "щука": "cá chó, cá măng",
    "щётка": "bàn chải, chổi",
    "этаж": "tầng nhà, lầu",
    "это": "đây là, đó là, cái này",
    "этот": "này, cái này",
    "юбка": "chân váy, váy",
    "юноша": "chàng trai trẻ, thanh niên",
    "язык": "ngôn ngữ, tiếng, cái lưỡi",
    "ярко": "rực rỡ, chói, sáng",
    "ёж": "con nhím gai",
    "ёрш": "cá ruff, cây cọ rửa chai",
    # 22 thẻ dưới đây lọt bộ lọc đầu tiên vì chúng chỉ dùng dấu CHẤM PHẨY để ngăn
    # nhóm nghĩa, không có ngoặc — đổi sang dấu phẩy cho cả kho cùng một lối.
    "жар": "cơn sốt, hơi nóng hầm hập",
    "край": "mép, rìa, bờ, vùng đất, miền",
    "ёлка": "cây vân sam nhỏ, cây thông Noel",
    "работа": "công việc, việc làm, chỗ làm",
    "средний": "ở giữa, trung bình, giống trung",
    "ручка": "bút bi, bút mực, tay nắm, núm vặn",
    "деревня": "làng nhỏ, xóm, vùng quê, nông thôn",
    "злой": "hung dữ, độc ác, đang cáu giận",
    "русский": "thuộc về nước Nga, người Nga, tiếng Nga",
    "счастливый": "hạnh phúc, may mắn",
    "институт": "viện nghiên cứu, học viện, trường đại học chuyên ngành",
    "бюст": "tượng bán thân, vòng ngực",
    "речь": "bài phát biểu, bài diễn văn, lời nói, cách nói năng",
    "борьба": "cuộc đấu tranh, sự vật lộn, môn đấu vật",
    "разъезд": "sự tản đi mỗi người một ngả, việc đi công tác, ga tránh tàu",
    "знакомство": "sự làm quen, mối quen biết",
    "академия": "viện hàn lâm, học viện",
    "почта": "bưu điện, thư từ, bưu phẩm",
    "форма": "hình dạng, khuôn, biểu mẫu, bộ đồng phục",
    "тысячный": "thứ một nghìn, hàng nghìn",
    "аудитория": "giảng đường, phòng học lớn, người nghe",
    "занятый": "bận rộn, đã bị chiếm chỗ",
    # Cặp hướng: `слева`/`справа` có ngoặc nên đã bị bắt, còn hai từ dưới thì không
    # — để nguyên là cặp viết theo hai lối khác nhau, đúng lỗi việc này đi sửa.
    "налево": "sang trái, về bên trái",
    "направо": "sang phải, về bên phải",
}


def main():
    apply = "--apply" in sys.argv
    if apply and not sync_truoc_khi_ghi_lo("don de bai tieng Viet"):
        return 1
    ids = _ac("findNotes", query='note:RU_Word')
    ban_do = {}
    for n in _ac("notesInfo", notes=ids):
        w = n["fields"]["WordClean"]["value"].replace("​", "").strip()
        ban_do.setdefault(w, []).append((n["noteId"],
                                         n["fields"].get("Vietnamese", {}).get("value", "")))
    doi, giong, thieu = 0, 0, []
    for w, moi in MOI.items():
        if w not in ban_do:
            thieu.append(w)
            continue
        for nid, cu in ban_do[w]:
            if cu == moi:
                giong += 1
                continue
            print(f"{w:18s} | {cu}\n{'':18s} -> {moi}")
            if apply:
                _ac("updateNoteFields", note={"id": nid, "fields": {"Vietnamese": moi}})
            doi += 1
    print(f"\ndoi {doi} note, {giong} note da dung san, {len(thieu)} tu KHONG tim thay")
    for w in thieu:
        print(f"  !! khong co note: {w}")
    if not apply:
        print("(chua ghi gi — them --apply de ghi that)")
    elif doi:
        print("sync: " + str(_ac("sync")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
